### Create a new user
POST http://localhost:3000/v1/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{$dotenv ID_TOKEN }}

{
    "username": "caster1",
    "profile": {
        "givenName": "John",
        "familyName": "NotGoodAtCasting",
        "nickName": "John",
        "displayName": "John NotGoodAtCasting",
        "preferredLanguage": "en",
        "gender": "GENDER_MALE"
    },
    "email": {
        "email": "john@ngac.com",
        "isVerified": true
    },
    "password": {
        "password": "Secr3tP4ssw0rd!",
        "changeRequired": false
    }
}
### Delete user
DELETE http://localhost:3000/v1/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{$dotenv ID_TOKEN }}

{
    "userId": "293502919024574467"
}

### Variables for different environments
@baseUrl = http://localhost:3000

### Create user using variable
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "293502919024574467",
    "firstName": "Jane",
    "lastName": "Smith",
    "email": "jane@example.com",
    "password": "password456"
}